FROM grafana/alloy:v1.16.1
COPY monitoring/alloy/config.alloy /etc/alloy/config.alloy
EXPOSE 12345
ENTRYPOINT ["/bin/alloy"]
CMD ["run", "--server.http.listen-addr=0.0.0.0:12345", "--storage.path=/var/lib/alloy/data", "--disable-reporting", "/etc/alloy/config.alloy"]
